Add dataloader for portrait segmentation
MaximIntegratedAI/ai8x-training pull request #111
Opened 2021-11-12 22:23 UTC by seldauyanik-maxim

Data loader module for AISegment: a portrait segmentation dataset is
added with several variants using high and low resolution images and
using disk or memory for data storage.

Training and evaluation scripts are added for training and evaluating
portrait segmentation dataset using high resolution UNET model

2021-11-16 15:34 UTC, rotx-maxim requested changes
See https://github.com/seldauyanik-maxim/ai8x-training/pull/1

2021-11-16 19:54 UTC, ermanok approved these changes
I only have a minor comment, rest looks good.

2021-11-16 21:22 UTC, MaximGorkem approved these changes
Looks good

2021-11-17 08:53 UTC, seldauyanik-maxim commented on scripts/evaluate_aisegment_unet.sh
> +python3 train.py --data /data2/ml/ --deterministic --model ai85unetlarge --dataset AISegment_352 --device MAX78000 --qat-policy qat_policy_aisegment.yaml --use-bias --evaluate -8 --exp-load-weights-f
First commit will be amended to add this option

2021-11-17 22:46 UTC, rotx-maxim approved these changes

2021-11-17 22:46 UTC, merged