Mobilenet
MaximIntegratedAI/ai8x-training pull request #125
Opened 2022-01-30 06:44 UTC by ermanok

2022-01-31 17:51 UTC, rotx-maxim reviewed
Please add comments to the model indicating it is for MAX78002 only.

2022-01-31 23:47 UTC, rotx-maxim approved these changes

2022-02-01 00:17 UTC, vicloginov reviewed
Looks good

2022-02-01 16:39 UTC, rotx-maxim requested changes
Please rename ai87net-mobilnet-v2.py to ai87net-mobilenet-v2.py (missing e)

2022-02-01 17:13 UTC, rotx-maxim approved these changes

2022-02-01 17:23 UTC, merged