Dataset/kinetics
MaximIntegratedAI/ai8x-training pull request #234
Opened 2023-06-15 17:36 UTC by alicangok

For image pairs, the updated dataloader now folds each image first, then concatenates the two.

This change was necessary to fill the data memory of the accelerator in a more efficient manner, as used in the demo.

2023-06-21 05:45 UTC, ermanok approved these changes
Looks good.

2023-06-22 20:57 UTC, rotx-maxim requested changes
Should we change the for loops to
images_concat = [torch.cat((x, y, dim=0)) for x, y in zip(images, images[1:])]
and
images_concat = [np.concatenate((x, y, axis=2)) for x, y in zip(images, images[1:])]

2023-06-25 15:36 UTC, alicangok commented
> Should we change the for loops to images_concat = [torch.cat((x, y, dim=0)) for x, y in zip(images, images[1:])] and images_concat = [np.concatenate((x, y, axis=2)) for x, y in zip(images, images[1:])]

Sure. `For` loops come more naturally to me than list comprehensions, but we could make that change for a marginal speed improvement.

2023-06-26 14:01 UTC, rotx-maxim approved these changes

2023-06-27 13:59 UTC, merged