Bayer2RGB network added to repository for debayerization.
MaximIntegratedAI/ai8x-training pull request #250
Opened 2023-09-12 12:03 UTC by asyatrhl

2023-09-12 21:30 UTC, rotx-maxim requested changes

2023-09-13 13:38 UTC, rotx-maxim requested changes

2023-09-13 13:38 UTC, rotx-maxim commented on scripts/train_bayer2rgb_imagenet.sh
remove --data /data_ssd

2023-09-13 13:38 UTC, rotx-maxim commented on scripts/evaluate_imagenet_bayer2rgb.sh
Remove --data /data_ssd

2023-09-13 19:17 UTC, rotx-maxim commented on train_all_models.sh
I think the final new line is missing from this file

2023-09-14 13:16 UTC, rotx-maxim approved these changes

2023-09-14 20:24 UTC, MaximGorkem approved these changes
Looks good.

2023-09-18 05:20 UTC, ermanok approved these changes
Looks good!

2023-09-18 13:13 UTC, merged