Update requirements.txt
MaximIntegratedAI/ai8x-training pull request #53
Opened 2020-12-12 19:25 UTC by batuhan-gundogdu

PyTSMod is for time-scale stretching to be used for augmentation of the KWS dataset. I am recommending to replace the librosa.effects-based function, which brings an undesired echo effect, due to phase mismatch in the Fourier domain.

2020-12-15 00:02 UTC, aniktash commented
Does dataset file of KWS need to be updated as well to replace librosa?

2020-12-15 09:23 UTC, batuhan-gundogdu commented
> Does dataset file of KWS need to be updated as well to replace librosa?

Yes, I'll do it in a minute.

2020-12-24 15:36 UTC, rotx-maxim requested changes
Please add the training script and training schedule

2020-12-30 20:35 UTC, rotx-maxim approved these changes

2020-12-30 20:36 UTC, merged