Feature develop merge tf2.4
MaximIntegratedAI/ai8x-training pull request #61
Opened 2021-01-14 22:43 UTC by aniktash

2021-01-14 22:51 UTC, aniktash commented
Intended to be TF 2.4, but downgraded to 2.3 for now to merge with latest develop.

2021-01-14 23:13 UTC, vicloginov commented on requirements-cu111.txt
>  opencv-python>=4.4.0
Add pytsmod>=0.3.3

2021-01-14 23:14 UTC, vicloginov reviewed
Add pytsmod>=0.3.3 to requirements-cu111.txt

2021-01-14 23:29 UTC, vicloginov approved these changes
Looks good

2021-01-15 01:59 UTC, rotx-maxim requested changes
There's a missing line break in requirements.txt
"tensorboard==2.4.0numba<0.50.0"

2021-01-15 16:48 UTC, merged